replicaCount: {{ replica_num }}

image:
  repository: skabrits/orca
  pullPolicy: Always
  tag: "0.1.0"

resources:
  limits:
    cpu: {{ cpu_num }}
    memory: {{ mem }}
  requests:
    cpu: {{ cpu_requests }}
    memory: {{ mem_requests }}

nodeSelector:
  openmpi-capable: "true"

sharedVolume:
  enabled: false

sharedMemory:
  enabled: {{ shm }}
  size: {{ shm_size }}

settings:
  taskMultiplier: 1
  args:
    - /bin/bash
    - '-c'
    - >-
      if [ "${NODE_NAME##*-}" = "0" ]; then
        unset OMPI_MCA_orte_default_hostfile;
        mkdir -p ~/results && cd ~/results;
        cat /tools/hosts | sed -e "s/\.[0-9a-zA-Z-]* / /g" -e "s/ max_slots=[0-9]*//g" -e "s/slots=/cpu=/g" > ~/results/results.nodes;
        echo -e '{{ file | replace("\n", "\\n") }}' > results.inp;
        "`echo $PATH | awk 'BEGIN{FS=":"; OFS="\n"} {$1=$1} 1' | grep orca | head -n 1`/orca" results.inp "--use-hwthread-cpus{{ additional_params }}" | tee results.out;
        cd .. ;
        zip -r  results.zip results;
        until cat results.zip | curl --header "X-Api-Key: {{ token }}" -X POST -T - http://{{ pod_ip }}:8888/upload; do echo "failed to upload"; sleep 10; done;
      else
        tail -f /dev/null;
      fi;